version: '3.8'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.9.3
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./vhost.d/:/etc/nginx/vhost.d:rw
      - ./certs/:/etc/nginx/certs/
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
